serverVersion = "5.0.1"

[log]
    level = "info"

[broker]
    # broker 监听的addr
    tcpAddr = "tcp://:1883"
    # 是否开启tls
    tcpTlsOpen = false


    # 开启websocket监听的addr
    wsAddr = ":8765"
    # websocket的path
    wsPath = "/mqtt"

    wssAddr=":8761"
    wssCertPath=""
    wssKeyPath=""

    # 根证书
    ca = "certs/root.crt"

[cluster]
    # 是否开启集群模式
    enabled = false
    # 当前节点再集群中的名称，必须保证每个节点的名称都不一样
    clusterName = "node1"
    # 集群模式监听的IP，用来和集群中其他节点通信
    clusterHost = "0.0.0.0"
    # 集群模式监听的端口
    clusterPort = 2884
    # 集群模式是否使用tls
    clusterTls = false
    # 服务器端证书
    serverCertFile = "certs/server.crt"
    # 服务器端秘钥
    serverKeyFile = "certs/server.key"
    # 客户端证书，如果集群节点通信开启了tls时需要使用
    clientCertFile = "certs/client.crt"
    # 客户端秘钥
    clientKeyFile = "certs/client.key"

[defaultConfig]
    [defaultConfig.connect]
        keepalive=300 # 单位s
        connectTimeOut=2 # 单位s
        ackTimeOut=20 #单位s
        timeOutRetries=3 # 超时重试次数
    [defaultConfig.provider]
        sessionsProvider=""
        topicsProvider=""
        authenticator="" # 不填则会采用默认，开启身份验证的验证钩子，可选【"default","mysql","redis"】

[store]
    [store.mysql]
        source = ""
        poolSize=10
    [store.redis]
        source=""
        db=1
        poolSize=10
[pprof]
port = 8080
open = true